# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
R:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev # for V8
      - valgrind  # for V8
