# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev       # for V8
      - valgrind        # for V8
      - libmagick++-dev # magick
